spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

  application:
    name: gulimall-third-party

server:
  port: 30000
#logging:
#  level:
#    com.ljf.gulimall.product: debug

